### ISSUE TITLE
remove okHttpClient singleton

### ISSUE THREAD

**Issue by theScrabi** [owncloud/android-library#357]
Remove the [okHttpClient signleton](https://github.com/owncloud/android-library/blob/af579a3fd0054d40d878fef896788c3631b54b8a/owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/http/HttpClient.java#L57) from [HttpCleint](https://github.com/owncloud/android-library/blob/master/owncloudComLibrary/src/main/java/com/owncloud/android/lib/common/http/HttpClient.java). Use propper injection which we can do from the OwnCloudClientFactory.

### Tasks
- [x] Make okHttpClient nonsingleton
- [x] move library remoteoperations to nonsingleton 
- [x] move app remoteoperations to nonsingleton
- [x] implement injection in library
  - [x] research
- [x] Add/fix Unit tests in library
- [x] Add/fix Unit tests in app
- [ ] Test if application runs stable

### Implementation
App: https://github.com/owncloud/android/pull/3047
Library: https://github.com/owncloud/android-library/pull/364
