### ISSUE TITLE
Replace Jackrabbit-webdav and deprecated/end-of-life HttpClient 3.1 libs with active and trustable WebDAV + HTTP client libraries

### ISSUE THREAD

**Issue by ghost** [owncloud/android-library#51]
Hi,

it seems the android-library is currently using the HttpClient libs in version 3.1 released in 2007. This has reached End-Of-Life in 2011 (https://hc.apache.org/httpclient-legacy/index.html).

Have you considered to move to the still maintananced https://hc.apache.org/ ?
___

Edited by @davigonz from here on
___

**ACs**

- [x] New library implementation should get rid of old endpoint (`/remote.php/webdav`) and start using the **new endpoint** (`/remote.php/dav/files/davUser/`). If something is still not implemented, open core issue. Have a look at the next **list of useful issues/PRs related to the new endpoint**:
  - https://github.com/owncloud/client/issues/4007
  - https://github.com/owncloud/client/pull/5332
  - https://github.com/owncloud/documentation/issues/2753
  - https://github.com/cernbox/smashbox/blob/master/protocol/protocol.md
___

**TOPICS TO DISCUSS**

- [x] How to update OwnCloudClient: 
  - **Option 1**: Extend OkHttpClient instead of HttpClient.
  - **Option 2**: Do not extend OkHttpClient and decouple it from OwnCloudClient, so that OkHttpClient can be easily used regardless of implementation details and OwnCloudClient is not too affected when upgrading OkHttpClient to future versions. 
- [x] How to implement the new WebDAV methods
  - **Option 1**: use a new wrapper for all the methods.
___

**TASKS**

- [X] Look for active and trustable WebDAV + HTTP client libraries. 
       Candidates: 
               1. **OKHttp 3.10.0**: https://github.com/square/okhttp
               2. ~~Sardine: https://github.com/lookfirst/sardine~~ Not enough active nor trustable
               3. ~~HttpUrlConnection: https://developer.android.com/reference/java/net/HttpURLConnection.html~~
- [x] Include new network library dependency. 
- [x] Use our [sample_client](https://github.com/owncloud/android-library/tree/master/sample_client) app to perform some tests:
  - GET to retrieve server status.
  - PROPFIND to read remote folder. 
- [x] Separate the previous tests in one branch for each candidate library:
  - OkHttp: https://github.com/owncloud/android-library/tree/test_ok_http
- [x] Implement basic requests by using the [sample client app](https://github.com/owncloud/android-library/tree/a2a1b0204a9f45f36e5575382bcc519742138e92/sample_client) and the new endpoint, without depending on ownCloud Android library => PR: https://github.com/owncloud/android-library/pull/187
  - [x] **Check server (GET):** show the server version 
  - [x] **Refresh (PROPFIND):** show the xml contained in propfind response with the list of files
  - [x] **Upload (PUT):** show successful message if the upload is properly performed.
  - [x] **Download (GET):** show successful message if the download is properly performed. The downloaded file won't be created locally in this stage. 
  - [x] **Delete remote (DELETE):** show successful message if the deletion is properly performed.
- [x] Having a look at the code of a different library and testing it 
- [x] Create wrapper with generic WebDAV and non WebDAV methods.
  - [x] WebDAV
    - [x] Propfind
    - [x] Copy
    - [x] Move
    - [x] Put
    - [x] MkCol
  - [x] Non WebDAV
    - [x] Get 
    - [x] Post
    - [x] Put
    - [x] Delete
- [x] Requests to implement, with the headers and properties required
  - **Files**  (WEBDAV - `/remote.php/dav/files/davUser/`): 
    - [x] UploadRemoteFileOperation => PUT
      - [x] Upload working
      - [x] Upload progress in notification bar and uploads view
      - [x] Cancel upload
      - [x] Retry upload
    - [ ] ChunkedUploadRemoteFileOperation, use new chunking=> PUT
      - [x] Upload working
      - [x] Upload progress in notification bar and uploads view 
      - [x] Cancel chunked upload
        - [x] Delete remote chunks folder when canceling upload
      - [x] Retry chunked upload
    - [x] DownloadRemoteFileOperation
    - [x] RemoveRemoteFileOperation
    - [x] CopyRemoteFileOperation => COPY
    - [x] RenameRemoteFileOperation => LOCALMOVE (MOVE)
    - [x] CreateRemoteFolderOperation => MKCOL
    - [x] ExistenceCheckRemoteOperation => PROPFIND
    - [x] MoveRemoteFileOperation => MOVE
    - [x] ReadRemoteFileOperation => PROPFIND
    - [x] ReadRemoteFolderOperation => PROPFIND
      - Request properties:
        - [x] creationdate
        - [x] quota-used-bytes
        - [x] permissions
        - [x] quota-available-bytes
        - [x] id
        - [x] getcontentlength
        - [x] size
        - [x] privatelink
  - **OAuth**:
    - [x] OAuth2GetAccessTokenOperation
    - [x] OAuth2RefreshAccessTokenOperation
  - **Shares** `/ocs/v1.php/apps/files_sharing/api/v1/shares`: 
    - [x] CreateRemoteShareOperation => POST
    - [x] GetRemoteShareesOperation => GET
    - [x] GetRemoteShareOperation => GET
    - [x] GetRemoteSharesForFileOperation => GET
    - [x] GetRemoteSharesOperation => GET
    - [x] RemoveRemoteShareOperation => DELETE
    - [x] UpdateRemoteShareOperation => PUT
  - **Status**:
    - [x] GetRemoteStatusOperation `/status.php` => GET
    - [x] GetRemoteCapabilitiesOperation `/ocs/v1.php/cloud/capabilities` => GET
  - **Users**:
    - [x] GetRemoteUserAvatarOperation `/index.php/avatar/`=> GET
    - [x] GetRemoteUserInfoOperation `/ocs/v1.php/cloud/user` => GET 
    - [x] GetRemoteUserQuotaOperation `/ocs/v1.php/cloud/users/username` => GET
- [x] Create custom interceptors to put user agent and credentials headers in all the requests.
- [x] Merge non ownCloud changes to dav4android by creating separate MRs
  - [x] Move method support: https://gitlab.com/bitfireAT/dav4android/merge_requests/2
  - [x] Copy method support: https://gitlab.com/bitfireAT/dav4android/merge_requests/3
  - [x] Include more WebDAV properties: https://gitlab.com/bitfireAT/dav4android/merge_requests/4
- [x] Update [sample client app](https://github.com/owncloud/android-library/tree/a2a1b0204a9f45f36e5575382bcc519742138e92/sample_client) to use the current library operations.
___
**TESTS**

[TO DO]
___

**RELATED ISSUES**

- [x] Send a unique X-Request-ID header to allow tracing requests in apache and owncloud logs https://github.com/owncloud/android/issues/2055
- [ ] Chunked upload and resuming: https://github.com/owncloud/android/issues/2070

**Comment by codeling** [comment]
Or maybe even better, moving to the [HttpURLConnection](https://developer.android.com/reference/java/net/HttpURLConnection.html) already included in android?

**Comment by codeling** [comment]
@masensio @davivel what's your take on this?
Further question: Is it possible that a dependency to such an old library causes gradle builds to fail? see https://github.com/mendhak/gpslogger/pull/316

**Comment by davivel** [comment]
@RealRancor, @codeling, sorry for the lack of response.

As @codeling said, the key point why HttpClient 3.1 is kept is that Jackrabbit-WebDAV depends on it. And depends on HttpClient 3.x, HttpClient 4.x is not backwards compatible with 3.x.

We just updated the version of Jackrabbit-Webdav (ready in master) and checked all the environment builds, including Gradle. We found no special problem. 

About considering a change: of course, several times. We searched for replacements of Jackrabbit-Webdav that depend on newer HTTP software, but had a hard time finding alternative easy-to-trust. We almost decided to go with https://github.com/lookfirst/sardine , but in the end didn't find the appropiate moment to go for it.

We'd rather not writing the code to parse WebDAV responses ourselves, since would take more time and would be prone to errors.

**Comment by davigonz** [comment]
> but in the end didn't find the appropiate moment to go for it.

This moment has arrived 🙌  , let's create some tasks...

**Comment by davigonz** [comment]
After playing a bit with OkHttp by using the test app included in our Android library, I conclude that it's possible to use Webdav methods but, as we expected time ago, we would need extra work to handle Webdav requests and responses since OkHttp doesn't include specific methods for Webdav as Jackrabbit-webdav did. Apart from that, the OkHttp library looks nice and it could fit in our app, but with some changes.

Related to the other library, [Sardine](https://github.com/lookfirst/sardine), is not as active as OkHttp and in addition to not including any reference to compatibility with Android, it depends on apache httpclient and there are some [opened issues](https://github.com/lookfirst/sardine/issues?q=is%3Aissue+android+is%3Aopen) about apache httpclient conflicts, similar to what I explained in #182, so IMHO, is not a trustable option. 

The request I've performed with our test app is one of our main requests, which is a PROPFIND to read the remote folder and works as expected, I will keep working on new requests with the test app before including the OkHttp library in our Android library.  

CC / @jesmrec @michaelstingl

**Comment by michaelstingl** [comment]
> is not a trustable option.

@davigonz Thank you for checking it!

@davigonz How could we test early if OkHttp plays well with MI-wrapping? /cc @ChrisEdS

**Comment by davigonz** [comment]
> How could we test early if OkHttp plays well with MI-wrapping? 

@michaelstingl I can adapt to OkHttp the first request the app performs to check the server, if the server is not reachable, tunneling is not working.

**Comment by ChrisEdS** [comment]
Yes @davigonz let's try with the test app. Please send it - i will try with wrapping and tunneling.

**Comment by davigonz** [comment]
This is ready and to be included in 0.9.21 version of the library and 2.9.0 version of the app.

**Comment by theScrabi** [comment]
Awesome :D
